import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import Pop from '../component/pop'
import styles from 'styles/Home.module.css'
import { getCookie } from 'typescript-cookie'
import Accueil from '../component/accueil'
import Login from '../component/login'
import Password from '../component/password'
import { fetchUserConnected } from '../services/Users/users.service'

export default function Home() {
  const [activated, setActivated] = useState<boolean>(false)
  const [connected, setConnected] = useState(<Login />)

  useEffect(() => {
    if(getCookie('authenticator') !== undefined){
      fetchUserConnected(getCookie('authenticator'))
      .then((data) => { 
        for(let i = 0; i<= data.groups.length; i++) {
          if(data.groups[i] === 'student') {
            setConnected(<Accueil userid={data.login} group='student'/>)
            break;
          }else if (data.groups[i] === 'admin'){
            setConnected(<Accueil userid={data.login} group='admin'/>)
            break
          }
      }; })
      .catch(() => { setConnected(<Login />) })
    }else{
      setConnected(<Login />)
    }
  }, [])

  const handleOnClick = (() => {
    setActivated(!activated)
  })
//npm i reactjs-popup --save
  return (
    <div>
      <Head>
      <title>Home</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="calendrier.ico" />
      </Head>
      <header className={styles.roll}>
        <Pop />
          <nav className={styles.rollbar}>
            <ul>
              <div className={styles.defile}><button className={styles.unrollbar} onClick={handleOnClick}>⏷</button>
                { activated && <div>
                <ul>
                <Link href='/planning'> Planning </Link>
                </ul></div>}
              </div>
            </ul>
          </nav>
       </header>
      {connected}
     </div>
  )
}
