import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from 'styles/Home.module.css'
import Calendar from '../component/calendar'
import { fetchTagsData } from '../services/Tags/tag.service'

export default function Test() {
  const [tags, setTags] = useState()
  useEffect(() => {
    fetchTagsData().then((data) => {
      setTags(data)
    })
  }, [])
  return (
    <div className={styles.icon}>
      <Head>
      <title>TEST</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="calendrier.ico" />
      </Head>
      <Calendar />
    </div>
  )
}
